module.exports = [
  {
    id: 1,
    position: "Ведущий специалист по информационной безопасности",
    company: "Почта России",
    location: "Москва, • Аэропорт",
    experience: "Требуемый опыт работы: 1–3 года",
    employment: "Полная занятость, полный день",
  },
  {
    id: 2,
    position: "Ведущий инженер / Инженер по информационной безопасности",
    company: "Utair",
    location: "Москва",
    experience: "Требуемый опыт работы: 3-6 лет",
    employment: "Полная занятость, удаленная работа",
  },
  {
    id: 3,
    position: "Специалист по защите информации",
    company: "МТС",
    location: "Москва",
    experience: "Требуемый опыт работы: 3-6 лет",
    employment: "Полная занятость, удаленная работа",
  },
  {
    id: 4,
    position: "Архитектор ИБ",
    company: "Северсталь",
    location: "Москва",
    experience: "Требуемый опыт работы: 1-3 года",
    employment: "Полная занятость, удаленная работа",
  },
  {
    id: 5,
    position: "Дежурный системный администратор",
    company: "Mango office",
    location: "Москва, •Калужская",
    experience: "Требуемый опыт работы: 1-3 года",
    employment: "Полная занятость",
  },
  {
    id: 6,
    position: "Системный администратор",
    company: "Мегафон",
    location: "Москва",
    experience: "Требуемый опыт работы: 3-6 лет",
    employment: "Полная занятость, удаленная работа",
  },
  {
    id: 7,
    position: "UX-дизайнер",
    company: "VK",
    location: "Москва, •Динамо",
    experience: "Требуемый опыт работы: 1-3 года",
    employment: "Полная занятость",
  },
  {
    id: 8,
    position: "Fronted разработчик",
    company: "Теле 2",
    location: "Москва, •Белорусская",
    experience: "Требуемый опыт работы: 3-6 лет",
    employment: "Полная занятость, удаленная работа",
  },
  {
    id: 9,
    position: "Fronted Developer",
    company: "Сбербанк",
    location: "Москва, •Комсомольская",
    experience: "Требуемый опыт работы: 3-6 лет",
    employment: "Полная занятость",
  },
  {
    id: 10,
    position: "Java developer",
    company: "ВТБ",
    location: "Москва, •Киевская",
    experience: "Требуемый опыт работы: 3-6 лет",
    employment: "Полная занятость",
  },
];
